explorer/urls.py
from django.conf.urls import url
from explorer.views import (
    QueryView,
    CreateQueryView,
    PlayQueryView,
    DeleteQueryView,
    ListQueryView,
    ListQueryLogView,
    DownloadFromSqlView,
    DownloadQueryView,
    StreamQueryView,
    EmailCsvQueryView,
    SchemaView,
    format_sql,
)

urlpatterns = [
    url(r'(?P<query_id>\d+)/$', QueryView.as_view(), name='query_detail'),
    url(r'(?P<query_id>\d+)/download$', DownloadQueryView.as_view(), name='download_query'),
    url(r'(?P<query_id>\d+)/stream$', StreamQueryView.as_view(), name='stream_query'),
    url(r'download$', DownloadFromSqlView.as_view(), name='download_sql'),
    url(r'(?P<query_id>\d+)/email_csv$', EmailCsvQueryView.as_view(), name='email_csv_query'),
    url(r'(?P<pk>\d+)/delete$', DeleteQueryView.as_view(), name='query_delete'),
    url(r'new/$', CreateQueryView.as_view(), name='query_create'),
    url(r'play/$', PlayQueryView.as_view(), name='explorer_playground'),
    url(r'schema/(?P<connection>.+)$', SchemaView.as_view(), name='explorer_schema'),
    url(r'logs/$', ListQueryLogView.as_view(), name='explorer_logs'),
    url(r'format/$', format_sql, name='format_sql'),
    url(r'^$', ListQueryView.as_view(), name='explorer_index'),
]

explorer/models.py
from __future__ import unicode_literals

import logging
from time import time
import six

from django.db import models, DatabaseError
try:
    from django.urls import reverse
except ImportError:
    from django.core.urlresolvers import reverse

from django.conf import settings

from explorer import app_settings
from explorer.utils import (
    passes_blacklist,
    swap_params,
    extract_params,
    shared_dict_update,
    get_s3_bucket,
    get_params_for_url,
    get_valid_connection
)

MSG_FAILED_BLACKLIST = "Query failed the SQL blacklist: %s"


logger = logging.getLogger(__name__)

@six.python_2_unicode_compatible
class Query(models.Model):
    title = models.CharField(max_length=255)
    sql = models.TextField()
    description = models.TextField(null=True, blank=True)
    created_by_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    last_run_date = models.DateTimeField(auto_now=True)
    snapshot = models.BooleanField(default=False, help_text="Include in snapshot task (if enabled)")
    connection = models.CharField(blank=True, null=True, max_length=128,
                                  help_text="Name of DB connection (as specified in settings) to use for this query. Will use EXPLORER_DEFAULT_CONNECTION if left blank")

    def __init__(self, *args, **kwargs):
        self.params = kwargs.get('params')
        kwargs.pop('params', None)
        super(Query, self).__init__(*args, **kwargs)

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Queries'

    def __str__(self):
        return six.text_type(self.title)

    def get_run_count(self):
        return self.querylog_set.count()

    def avg_duration(self):
        return self.querylog_set.aggregate(models.Avg('duration'))['duration__avg']

    def passes_blacklist(self):
        return passes_blacklist(self.final_sql())

    def final_sql(self):
        return swap_params(self.sql, self.available_params())

    def execute_query_only(self):
        return QueryResult(self.final_sql(), get_valid_connection(self.connection))

    def execute_with_logging(self, executing_user):
        ql = self.log(executing_user)
        ret = self.execute()
        ql.duration = ret.duration
        ql.save()
        return ret, ql

    def execute(self):
        ret = self.execute_query_only()
        ret.process()
        return ret

    def available_params(self):
        """
            Merge parameter values into a dictionary of available parameters

        :param param_values: A dictionary of Query param values.
        :return: A merged dictionary of parameter names and values. Values of non-existent parameters are removed.
        """

        p = extract_params(self.sql)
        if self.params:
            shared_dict_update(p, self.params)
        return p

    def get_absolute_url(self):
        return reverse("query_detail", kwargs={'query_id': self.id})

    @property
    def params_for_url(self):
        return get_params_for_url(self)

    def log(self, user=None):
        if user:
            # In Django<1.10, is_anonymous was a method.
            try:
                is_anonymous = user.is_anonymous()
            except TypeError:
                is_anonymous = user.is_anonymous
            if is_anonymous:
                user = None
        ql = QueryLog(sql=self.final_sql(), query_id=self.id, run_by_user=user, connection=self.connection)
        ql.save()
        return ql

    @property
    def shared(self):
        return self.id in set(sum(app_settings.EXPLORER_GET_USER_QUERY_VIEWS().values(), []))

    @property
    def snapshots(self):
        if app_settings.ENABLE_TASKS:
            b = get_s3_bucket()
            keys = b.list(prefix='query-%s/snap-' % self.id)
            keys_s = sorted(keys, key=lambda k: k.last_modified)
            return [SnapShot(k.generate_url(expires_in=0, query_auth=False),
                             k.last_modified) for k in keys_s]


class SnapShot(object):

    def __init__(self, url, last_modified):
        self.url = url
        self.last_modified = last_modified


class QueryLog(models.Model):

    sql = models.TextField(null=True, blank=True)
    query = models.ForeignKey(Query, null=True, blank=True, on_delete=models.SET_NULL)
    run_by_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    run_at = models.DateTimeField(auto_now_add=True)
    duration = models.FloatField(blank=True, null=True)  # milliseconds
    connection = models.CharField(blank=True, null=True, max_length=128)

    @property
    def is_playground(self):
        return self.query_id is None

    class Meta:
        ordering = ['-run_at']


class QueryResult(object):

    def __init__(self, sql, connection):

        self.sql = sql
        self.connection = connection

        cursor, duration = self.execute_query()

        self._description = cursor.description or []
        self._data = [list(r) for r in cursor.fetchall()]
        self.duration = duration

        cursor.close()

        self._headers = self._get_headers()
        self._summary = {}

    @property
    def data(self):
        return self._data or []

    @property
    def headers(self):
        return self._headers or []

    @property
    def header_strings(self):
        return [str(h) for h in self.headers]

    def _get_headers(self):
        return [ColumnHeader(d[0]) for d in self._description] if self._description else [ColumnHeader('--')]

    def _get_numerics(self):
        if hasattr(self.connection.Database, "NUMBER"):
            return [ix for ix, c in enumerate(self._description) if hasattr(c, 'type_code') and c.type_code in self.connection.Database.NUMBER.values]
        elif self.data:
            d = self.data[0]
            return [ix for ix, _ in enumerate(self._description) if not isinstance(d[ix], six.string_types) and six.text_type(d[ix]).isnumeric()]
        return []

    def _get_transforms(self):
        transforms = dict(app_settings.EXPLORER_TRANSFORMS)
        return [(ix, transforms[str(h)]) for ix, h in enumerate(self.headers) if str(h) in transforms.keys()]

    def column(self, ix):
        return [r[ix] for r in self.data]

    def process(self):
        start_time = time()

        self.process_columns()
        self.process_rows()

        logger.info("Explorer Query Processing took %sms." % ((time() - start_time) * 1000))

    def process_columns(self):
        for ix in self._get_numerics():
            self.headers[ix].add_summary(self.column(ix))

    def process_rows(self):
        transforms = self._get_transforms()
        if transforms:
            for r in self.data:
                for ix, t in transforms:
                    r[ix] = t.format(str(r[ix]))

    def execute_query(self):
        cursor = self.connection.cursor()
        start_time = time()

        try:
            cursor.execute(self.sql)
        except DatabaseError as e:
            cursor.close()
            raise e

        return cursor, ((time() - start_time) * 1000)


@six.python_2_unicode_compatible
class ColumnHeader(object):

    def __init__(self, title):
        self.title = title.strip()
        self.summary = None

    def add_summary(self, column):
        self.summary = ColumnSummary(self, column)

    def __str__(self):
        return self.title


@six.python_2_unicode_compatible
class ColumnStat(object):

    def __init__(self, label, statfn, precision=2, handles_null=False):
        self.label = label
        self.statfn = statfn
        self.precision = precision
        self.handles_null = handles_null

    def __call__(self, coldata):
        self.value = round(float(self.statfn(coldata)), self.precision) if coldata else 0

    def __str__(self):
        return self.label


@six.python_2_unicode_compatible
class ColumnSummary(object):

    def __init__(self, header, col):
        self._header = header
        self._stats = [
            ColumnStat("Sum", sum),
            ColumnStat("Avg", lambda x: float(sum(x)) / float(len(x))),
            ColumnStat("Min", min),
            ColumnStat("Max", max),
            ColumnStat("NUL", lambda x: int(sum(map(lambda y: 1 if y is None else 0, x))), 0, True)
        ]
        without_nulls = list(map(lambda x: 0 if x is None else x, col))

        for stat in self._stats:
            stat(col) if stat.handles_null else stat(without_nulls)

    @property
    def stats(self):
        return {c.label: c.value for c in self._stats}

    def __str__(self):
        return str(self._header)

explorer/forms.py
from django.db import DatabaseError
from django.forms import ModelForm, Field, ValidationError, BooleanField, CharField
from django.forms.widgets import CheckboxInput, Select

from explorer.app_settings import EXPLORER_DEFAULT_CONNECTION, EXPLORER_CONNECTIONS
from explorer.models import Query, MSG_FAILED_BLACKLIST


class SqlField(Field):

    def validate(self, value):
        """
        Ensure that the SQL passes the blacklist.

        :param value: The SQL for this Query model.
        """

        query = Query(sql=value)

        passes_blacklist, failing_words = query.passes_blacklist()

        error = MSG_FAILED_BLACKLIST % ', '.join(failing_words) if not passes_blacklist else None

        if error:
            raise ValidationError(
                error,
                code="InvalidSql"
            )


class QueryForm(ModelForm):

    sql = SqlField()
    snapshot = BooleanField(widget=CheckboxInput, required=False)
    connection = CharField(widget=Select, required=False)

    def __init__(self, *args, **kwargs):
        super(QueryForm, self).__init__(*args, **kwargs)
        self.fields['connection'].widget.choices = self.connections
        if not self.instance.connection:
            self.initial['connection'] = EXPLORER_DEFAULT_CONNECTION
        self.fields['connection'].widget.attrs['class'] = 'form-control'

    def clean(self):
        if self.instance and self.data.get('created_by_user', None):
            self.cleaned_data['created_by_user'] = self.instance.created_by_user
        return super(QueryForm, self).clean()

    @property
    def created_by_user_email(self):
        return self.instance.created_by_user.email if self.instance.created_by_user else '--'

    @property
    def created_at_time(self):
        return self.instance.created_at.strftime('%Y-%m-%d')

    @property
    def connections(self):
        return [(v, k) for k, v in EXPLORER_CONNECTIONS.items()]

    class Meta:
        model = Query
        fields = ['title', 'sql', 'description', 'snapshot', 'connection']

explorer/templates/explorer/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SQL Explorer{% if query %} - {{ query.title }}{% elif title %} - {{ title }}{% endif %}</title>

    <link href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.36.0/codemirror.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/pivottable/2.20.0/pivot.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'explorer/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'explorer/explorer.css' %}" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

    <script src="{% static 'explorer/jquery-ui.min.js' %}"></script>
    <script src="{% static 'explorer/explorer.js' %}"></script>
    <script type="text/javascript">
        queryId = "{% firstof query.id 'new' %}";
    </script>
</head>

<body>
  {% block sql_explorer_content_takeover %}
    <div id="wrap" class="wrap">
        {% block sql_explorer_navbar %}
            <div class="navbar navbar-default navbar-static-top" role="navigation">
              <div class="container">
                <div class="navbar-header">
                  <a class="navbar-brand" href="{% url "explorer_index" %}">SQL Explorer</a>
                </div>
                <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                    {% block sql_explorer_navlinks %}{% endblock %}
                  </ul>
                </div>
              </div>
            </div>
        {% endblock %}
        <div class="container">
          <div class="starter-template">
          {% block sql_explorer_content %}{% endblock %}
          </div>
        </div>
    </div>
  {% endblock %}
    {% block sql_explorer_footer %}
        <div class="container">
            <div class="row">
              <div class="col-md-12 text-center">
                    <p class="text-muted">
                        Powered by <a href="https://www.github.com/groveco/django-sql-explorer/">django-sql-explorer</a> from
                        <a href="https://www.grove.co">Grove Collaborative</a>. Rendered at {% now "SHORT_DATETIME_FORMAT" %}
                    </p>
              </div>
            </div>
        </div>
    {% endblock %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.36.0/codemirror.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.36.0/mode/sql/sql.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.36.0/addon/comment/comment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/floatthead/2.1.1/jquery.floatThead.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pivottable/2.20.0/pivot.min.js"></script>
    {% block sql_explorer_scripts %}{% endblock %}
</body>

</html>

explorer/templates/explorer/export_buttons.html
{% for key, name in exporters %}
    {% if query and query.id %}
        {% if query.params %}
          <li><a href="{% url "download_query" query.id %}?format={{ key }}&params={{ query.params_for_url }}">{{ name }}</a></li>
        {% else %}
          <li><a href="{% url "download_query" query.id %}?format={{ key }}">{{ name }}</a></li>
        {% endif %}
    {% else %}
        <li><input type="submit" value="{{ name }}" data-format="{{ key }}" class="download-button btn btn-link" /></li>
    {% endif %}
{% endfor %}

explorer/templates/explorer/fullscreen.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SQL Explorer{% if query %} - {{ query.title }}{% elif title %} - {{ title }}{% endif %}</title>

    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'explorer/explorer.css' %}" />

</head>

<body>
  <h2>{% if query %}{{ query.title }}{% if shared %}<small>&nbsp;&nbsp;shared</small>{% endif %}{% else %}New Query{% endif %}</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        {% for h in headers %}
          <th>{{ h }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody class="list">
      {% if data %}
        {% for row in data %}
          <tr class="data-row">
            {% for i in row %}
              {% if unsafe_rendering %}
                <td>{% autoescape off %}{{ i }}{% endautoescape %}</td>
              {% else %}
                <td>{{ i }}</td>
              {% endif %}
            {% endfor %}
          </tr>
        {% endfor %}
      {% else %}
        <tr class="text-center"><td colspan="{{ headers|length }}">Empty Resultset</td></tr>
      {% endif %}
    </tbody>
  </table>
</body>
</html>

explorer/templates/explorer/params.html
{% if params %}
<div class="panel-footer">
  <div class="form-inline">
  {% for k, v in params.items %}
      <div class="form-group">
          <label for="{{ k }}_param" class="control-label col-sm-4">{{ k }}:</label>
          <div class="col-sm-7">
              <input type="text" data-param="{{ k }}" class="param form-control" name="{{ k }}_param" id="{{ k }}_param" placeholder="parameter" value="{{ v }}" />
          </div>
          <div class="col-sm-1"></div>
      </div>
  {% endfor %}
  </div>
</div>
{% endif %}

explorer/templates/explorer/pdf_template.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
    <table>
        <thead>
            <tr>
                {% for h in headers %}
                    <th>{{ h }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                {% for col in row %}
                    <td>{{ col }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

explorer/templates/explorer/play.html
{% extends "explorer/base.html" %}

{% load explorer_tags %}

{% block sql_explorer_navlinks %}
    {% if can_change %}
      <li><a href="{% url "query_create" %}">New Query</a></li>
      <li class="active"><a href="">Playground</a></li>
      <li><a href="{% url "explorer_logs" %}">Logs</a></li>
    {% endif %}
{% endblock %}

{% block sql_explorer_content %}
<div class="row">
    <div id="query_area" class="col-md-12">
        <h2>Playground</h2>
        <p>The playground is for experimenting and writing ad-hoc queries. By default, nothing you do here will be saved.</p>
        <form role="form" action="{% url "explorer_playground" %}" method="post" id="editor" class="playground-form form-horizontal">{% csrf_token %}
            {% if error %}
                <div class="alert alert-danger">{{ error|escape }}</div>
            {% endif %}
            {% if form.connections|length > 1 %}
              <div class="form-group">
                <label for="id_connection" class="col-sm-2 control-label">Connection</label>
                <div class="col-sm-10">
                  {{ form.connection }}
                </div>
              </div>
            {% else %}
              {# still need to submit the connection, just hide the UI element #}
              <div class="hidden">
                {{ form.connection }}
              </div>
            {% endif %}
            <div class="panel panel-default sql-panel">
                <div class="panel-heading">
                  <div class="row">
                    <div class="col-md-6">
                      <span class="panel-title">Playground SQL</span>
                    </div>
                    {% if ql_id %}
                        <div class="col-md-6 text-right">
                          <small><a href="{% url "explorer_playground" %}?querylog_id={{ ql_id }}"><i class="glyphicon glyphicon-link"></i></a></small>
                        </div>
                    {% endif %}
                  </div>
                </div>
                <div class="panel-content">
                    <textarea class="form-control" cols="40" id="id_sql" name="sql" rows="20">{{ query.sql }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="text-center">
                  <div class="btn-group">
                    <input type="submit" value="Refresh" id="refresh_play_button" class="btn btn-default"/>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="caret"></span>
                      <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><input type="submit" value="Save As New Query" id="create_button" class="btn btn-link"/></li>
                    </ul>
                  </div>
                  <div class="btn-group">
                    <label class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Download</label>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="caret"></span>
                      <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                      {% export_buttons query %}
                    </ul>
                  </div>

                  <button type="button" class="btn btn-default" id="show_schema_button">Show Schema</button>
                  <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">Hide Schema</button>
                  <button type="button" class="btn btn-default" id="format_button">Format</button>
                </div>
            </div>
            <input type="hidden" value="Playground Query" name="title" />
        </form>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="about:blank" height="828px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>
{% include 'explorer/preview_pane.html' %}

{% endblock %}

{% block sql_explorer_scripts %}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId);
        });
    </script>
{% endblock %}

explorer/templates/explorer/query.html
{% extends "explorer/base.html" %}

{% load explorer_tags %}

{% block sql_explorer_navlinks %}
    {% if can_change %}
      <li{% if not query %} class="active" {% endif %}><a href="{% url "query_create" %}">New Query</a></li>
      <li><a href="{% url "explorer_playground" %}">Playground</a></li>
    {% endif %}
    {% if query %}<li class="active"><a href="">Query Detail</a></li>{% endif %}
    <li><a href="{% url "explorer_logs" %}">Logs</a></li>
{% endblock %}

{% block sql_explorer_content %}
<div class="row">
    <div id="query_area" class="query-area col-md-12">
        <h2>{% if query %}{{ query.title }}{% if shared %}<small>&nbsp;&nbsp;shared</small>{% endif %}{% else %}New Query{% endif %}</h2>
        {% if query %}
            <div class="text-right">
                <a href="{% url "explorer_logs" %}?query_id={{ query.id }}"><h2 class="small">History</h2></a>
            </div>
        {% endif %}
        {% if message %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
        <div>
            {% if query %}
                <form role="form" class="form-horizontal" action="{% url "query_detail" query.id %}" method="post" id="editor">{% csrf_token %}
            {% else %}
                <form role="form" class="form-horizontal" action="{% url "query_create" %}" method="post" id="editor">{% csrf_token %}
            {% endif %}
                {% if error %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endif %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {% if form.title.errors %}{% for error in form.title.errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}{% endif %}
                    <label for="id_title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="id_title" maxlength="255" name="title" type="text" {% if not can_change %}disabled{% endif %} value="{{ form.title.value|default_if_none:"" }}" />
                    </div>
                  {% if form.connections|length > 1 and can_change %}
                    </div>
                    <div class="form-group">
                      <label for="id_connection" class="col-sm-2 control-label">Connection</label>
                      <div class="col-sm-10">
                        {{ form.connection }}
                      </div>
                  {% else %}
                    {# still need to submit the connection, just hide the UI element #}
                    <div class="hidden">
                      {{ form.connection }}
                    </div>
                  {% endif %}
                </div>
                <div class="form-group">
                    {% if form.description.errors %}
                        <div class="alert alert-danger">{{ form.description.errors }}</div>
                    {% endif %}
                    <label for="id_description" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" cols="40" id="id_description" name="description" {% if not can_change %}disabled{% endif %} rows="2">{{ form.description.value|default_if_none:"" }}</textarea>
                    </div>
                </div>
                <input type="hidden" id="id_created_by_user" name="created_by_user" value="{{ form.created_by_user_email }}" />
                {% if form.sql.errors %}{% for error in form.sql.errors %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endfor %}{% endif %}
                <div class="panel panel-default sql-panel">
                    <div class="panel-heading">
                      <div class="row">
                        <div class="col-md-6">
                          <span class="panel-title">SQL</span>
                        </div>
                        <div class="col-md-6 text-right">
                          {% if query %}
                            <small><a href="#" title="Open in playground" id="playground_button"><i class="glyphicon glyphicon-new-window"></i></a></small>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                    <div class="panel-content">
                        <textarea class="form-control" {% if not can_change %} disabled {% endif %} cols="40" id="id_sql" name="sql" rows="20">{{ form.sql.value|default_if_none:"" }}</textarea>
                    </div>
                    {% if params %}
                      {% include 'explorer/params.html' %}
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="text-center">
                        {% if can_change %}
                            <div class="btn-group">
                              <input type="submit" value="Save & Run" class="btn btn-default" id="save_button" />
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu">
                                {% export_buttons query %}
                                <li role="separator" class="divider"></li>
                                <li><input type="submit" value="Save Only" class="btn btn-link" id="save_only"/></li>
                              </ul>
                            </div>
                            <button type="button" class="btn btn-default" id="show_schema_button">Show Schema</button>
                            <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">Hide Schema</button>
                            <button type="button" class="btn btn-default" id="format_button">Format</button>
                        {% else %}
                            <input type="submit" value="Refresh" class="btn btn-default" id="refresh_button" />
                            <div class="btn-group">
                              <label class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Download</label>
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu">
                                {% export_buttons query %}
                              </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>

            </form>
        </div>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="" height="828px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>
{% include 'explorer/preview_pane.html' %}
<div class="row">
  <div class="col-md-6">
    {% if query and can_change and tasks_enabled %}
      {{ form.snapshot }} Snapshot
    {% endif %}
  </div>
  <div class="col-md-6 text-right">
    <small>
      {% if query.avg_duration %}
        Avg. execution: {{ query.avg_duration|floatformat:2 }}ms. Query created by {{ form.created_by_user_email }} on {{ form.created_at_time }}.
      {% endif %}
    </small>
  </div>
</div>
{% endblock %}

{% block sql_explorer_scripts %}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId);
        });
    </script>
{% endblock %}

explorer/templates/explorer/query_confirm_delete.html
{% extends "explorer/base.html" %}

{% block sql_explorer_content %}
    <form method="post">{% csrf_token %}
        <div class="alert alert-info">
            Are you sure you want to delete "{{ object.title }}" ?
        </div>
        <div>
            <input type="submit" value="Delete Query" class="btn btn-default" />
        </div>
    </form>
{%  endblock %}

explorer/templates/explorer/schema_building.html
{% extends "explorer/base.html" %}


{% block sql_explorer_content_takeover %}

  <div class="schema-wrapper">
    <h4 class="text-center">Schema is building...</h4>
    <div>Please wait a minute, and refresh.</div>
  </div>

{% endblock %}